name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install mecab-ipadic
      run: sudo apt install mecab-ipadic-utf8
    - name: Build
      run: |
        git submodule update --init --recursive
        make configure
        make debug
    - name: Run tests
      run: make test_debug DUCKDB_PLATFORM=$(cat configure/platform.txt)
