name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        duckdb_version: ["1.4.5", "1.5.4"]

    steps:
    - uses: actions/checkout@v6
    - name: Install mecab-ipadic
      run: sudo apt install mecab-ipadic-utf8
    - name: Build
      run: |
        git submodule update --init --recursive
        make configure DUCKDB_VERSION=${{ matrix.duckdb_version }}
        make debug DUCKDB_VERSION=${{ matrix.duckdb_version }}
    - name: Run tests
      run: make test DUCKDB_VERSION=${{ matrix.duckdb_version }}
